services:
    server:
        image: nginx:latest
        volumes:
            - ./frontend/templates:/etc/nginx/templates
            - ./frontend/public:/usr/share/nginx/html:ro
        ports:
            - 80:80
    node:
        image: node:18.16.1-slim
        volumes:
            - ./backend:/app
        working_dir: /app
        ports:
            - 3000:3000
        command: node index.js

    